disabled = false
locale = "en"
label = "English"
weight = 1
title = "Home"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Nicoline Visby"
  email = "nnvisby01@gmail.com"
  image = "img/profile.jpg"
  imageQuality = 96
  headline = "Software Developer in training"
  bio = "Currently developing my coding skills by building exciting and innovative applications."
    links = [
      { email = "nnvisby01@gmail.com" },
      { github = "https://github.com/NicolineNV" },
      { linkedin = "https://www.linkedin.com/in/nicoline-visby-8a3757206/" },
    ]
